version: '3.8'

services:
  paula-chocolat-back:
    build:
      context: ./Docker-back
      dockerfile: Dockerfile
    container_name: paula-chocolat-back
    ports:
      - "3000:3000"
    volumes:
      # Mapeia o diretório que contém o banco de dados SQLite
      - sqlite-data:/usr/src/app
    networks:
      - chocolat-network

  paula-chocolat-front:
    build:
      context: ./Docker-front
      dockerfile: Dockerfile
    container_name: paula-chocolat-front
    ports:
      - "80:80"
    depends_on:
      - paula-chocolat-back
    environment:
      # Variável de ambiente para o frontend se conectar ao backend
      API_URL: http://paula-chocolat-back:3000
    networks:
      - chocolat-network

networks:
  chocolat-network:
    driver: bridge

volumes:
  sqlite-data:
    driver: local
